Astorozhevsky/token in cookies
RonasIT/angular-common pull request #16
Opened 2022-05-09 10:46 UTC by astorozhevsky

2022-05-09 10:47 UTC, astorozhevsky commented
@dmitryusenko @ipakhomov could you please review?

2022-05-10 05:21 UTC, dmitryusenko reviewed
@astorozhevsky 

Looks good to me overall! I just left a few comments that we might need to address.

2022-05-10 05:21 UTC, dmitryusenko commented on common/src/auth/auth.service.ts
> +          delete this.processingTokenRefresh$;
@astorozhevsky 

Can we set it to `null` instead, and extend the typing of this field to `Observable<HttpResponse<void>> | null`?

2022-05-10 05:21 UTC, dmitryusenko commented on common/src/auth/auth.service.ts
> +          delete this.processingTokenRefresh$;
@astorozhevsky 

Same here, I think we should set it to `null`.

2022-05-10 05:21 UTC, dmitryusenko commented on common/src/auth/auth.service.ts
> +    let isAuthenticated = this.cookieService.get(this.authConfig.isAuthenticatedField ?? AuthService.DEFAULT_IS_AUTHENTICATED_FIELD);
@astorozhevsky 

We could use `const` instead of `let` here.

2022-05-10 05:21 UTC, dmitryusenko commented on common/src/auth/auth.service.ts
> +    let remember = this.cookieService.get('remember');
@astorozhevsky 

We could use `const` instead of `let` here.

2022-05-17 06:03 UTC, ipakhomov requested changes

2022-05-17 06:03 UTC, ipakhomov commented on common/src/auth/interceptors/token-expired.ts
> +                switchMap(() => next.handle(request))
Not sure, but shouldn't we also call `this.authService.unauthorize();` in case of token refresh failure as this was in the former implementation?

2022-05-17 06:03 UTC, ipakhomov commented on common/src/auth/auth.service.ts
> +    const remember = this.cookieService.get('remember');
I'd make the `remember` key to be also configurable for bit more flexibility

2022-05-18 05:52 UTC, astorozhevsky commented on common/src/auth/interceptors/token-expired.ts
> +            response.error.error === JwtExceptions.TOKEN_EXPIRED &&
[This checking](https://github.com/RonasIT/angular-common/blob/astorozhevsky/token-in-cookies/common/src/auth/auth.service.ts#L91) will allow only one token refresh request. So, I think checking if a request isn't the token refresh request will be redundant here.

Please let me know if I understand you wrong.

2022-05-18 07:32 UTC, ipakhomov approved these changes

2022-05-19 04:47 UTC, merged