Implemented CookieModule
RonasIT/angular-common pull request #19
Opened 2022-05-27 06:56 UTC by VladimirGlinskii

2022-05-30 03:56 UTC, astorozhevsky requested changes

2022-05-30 03:56 UTC, astorozhevsky commented on common/src/cookie/cookie.module.ts
> +    if (config?.requestToken && config?.responseToken) {
```suggestion

    if (config?.requestToken && config?.responseToken) {
```

2022-05-30 03:56 UTC, astorozhevsky commented on common/src/cookie/cookie.service.ts
> +    let cookieString = encodeURIComponent(name) + '=' + encodeURIComponent(value) + ';';
can we use `Template literals` here?

2022-05-30 03:56 UTC, astorozhevsky commented on common/src/cookie/cookie.service.ts
> +      cookieString += 'expires=' + options.expires.toUTCString() + ';';
can we use `Template literals` here?

2022-05-30 03:56 UTC, astorozhevsky commented on common/src/cookie/cookie.service.ts
> +      cookieString += 'Max-Age=' + options.maxAge + ';';
can we use `Template literals` here?

2022-05-30 03:56 UTC, astorozhevsky commented on common/src/cookie/cookie.service.ts
> +      cookieString += 'path=' + options.path + ';';
can we use `Template literals` here?

2022-05-30 03:56 UTC, astorozhevsky commented on common/src/cookie/cookie.service.ts
> +      cookieString += 'domain=' + options.domain + ';';
can we use `Template literals` here?

2022-05-30 03:56 UTC, astorozhevsky commented on common/src/cookie/cookie.service.ts
> +      cookieString += 'secure;';
can we use `Template literals` here?

2022-05-30 03:56 UTC, astorozhevsky commented on common/src/cookie/cookie.service.ts
> +      cookieString += 'sameSite=' + options.sameSite + ';';
can we use `Template literals` here?

2022-05-30 03:56 UTC, astorozhevsky commented
@ipakhomov @dmitryusenko could you please review?

2022-05-30 12:55 UTC, dmitryusenko commented on common/src/cookie/cookie.module.ts
> +      )
```suggestion
      );
```

2022-05-30 12:55 UTC, dmitryusenko commented on common/src/cookie/cookie.service.ts
> +    return null;
```suggestion
    const regExp: RegExp = this.getCookieRegExp(encodeURIComponent(key));
    const result: RegExpExecArray = regExp.exec(this.cookieString);

    return (result !== null)
      ? decodeURIComponent(result[1])
      : null;
```

2022-05-30 12:55 UTC, dmitryusenko commented on common/src/cookie/cookie.service.ts
> +  public check(key: TKey): boolean {
@VladimirGlinskii 

Maybe we don't need this method. If it's needed, then we could rename it to `has`.

2022-05-30 12:55 UTC, dmitryusenko commented on common/src/cookie/cookie.service.ts
> +        cookies[decodeURIComponent(currentCookie[0])] = decodeURIComponent(currentCookie[1]);
```suggestion
        const [name, value] = split.split('=');
        cookies[decodeURIComponent(name)] = decodeURIComponent(value);
```

2022-05-30 12:57 UTC, dmitryusenko commented on common/src/cookie/cookie.service.ts
> +  public getObject(name: TKey): object | null {
@VladimirGlinskii 

We should unify the `TKey` argument name. In some methods it is named `key` and in other methods it's called `name`.

2022-06-01 05:02 UTC, VladimirGlinskii commented
@astorozhevsky, @dmitryusenko Fixed your remarks.

2022-06-01 05:14 UTC, astorozhevsky approved these changes

2022-06-01 15:10 UTC, ipakhomov approved these changes
Looks good to me!

2022-06-02 01:03 UTC, merged